### ISSUE TITLE
System.TypeLoadException : Could not load type 'NSubstitute.Core.ConfigureCall' from assembly 'NSubstitute

### ISSUE THREAD

**Issue by ghost** [consulo/consulo-nunit#3]
Problem occurs in Consulo when running NUnit test with nsubstitute mock. I think the problem is somewhere in consulo NUnit plugin because I can run tests on this binary with nunit-console in terminal by hand and those pass without any problems using exactly same nsubstitute dll file.

```
/usr/bin/mono /home/eyveer/.ConsuloData/config/plugins/mono-dotnet/loader/loader.exe /home/eyveer/.ConsuloData/config/plugins/nunit/nunit-ext.dll /home/eyveer/lib/NUnit-2.6.4/bin/lib consulo_nunit_wrapper.Program /home/eyveer/ConsuloProjects/untitled1/out/production/untitled1/untitled1.exe 35009
Testing started at 11:50 ...

System.TypeLoadException : Could not load type 'NSubstitute.Core.ConfigureCall' from assembly 'NSubstitute, Version=0.0.0.0, Culture=neutral, PublicKeyToken=92dd2e9066daa5ca'.
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
```

**Comment by VISTALL** [comment]
U can provide simple project ?

**Comment by ghost** [comment]
http://narciarska2f.pl/untitled1.tar.gz

Tried with downloaded NSubstitute.dll and one I compiled myself. Problem is same with both.

**Comment by VISTALL** [comment]
reproduced

**Comment by ghost** [comment]
```
eyveer@eyveer:~$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

eyveer@eyveer:~$ mono --version
Mono JIT compiler version 3.12.0 (tarball Mon Jan 19 14:55:43 UTC 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        LLVM:          supported, not enabled.
        GC:            sgen

eyveer@eyveer:~$ nunit-console --version
NUnit-Console version 2.6.3.0
   OS Version: Unix 3.16.0.30
  CLR Version: 4.0.30319.17020 ( Mono 4.0 ( 3.12.0 (tarball Mon Jan 19 14:55:43 UTC 2015) ) )

```

just in case

**Comment by VISTALL** [comment]
Strange. I was think that library dependencies dont loaded. But i created nested module, and it works.

**Comment by VISTALL** [comment]
No idea that a problem

**Comment by ghost** [comment]
aw :(
btw, is there a way to build consulos project from terminal? Without .csproj and .sln xbuild wont work and for mcs I would need to write solid makefile i think.
builing in IDE and running from terminal would be annoying.

**Comment by VISTALL** [comment]
Yes and no. Consulo platform support external building - but it required Consulo and plugins. I am using it at build server http://must-be.org/vulcan/

But i dont have - special command line for it. I implemented it here https://github.com/must-be/must-be.org/tree/master/vulcan/plugins/vulcan-consulo

**Comment by VISTALL** [comment]
Found problem.

Its a assembly conflict.  

NUnit have /bin/lib/NSubstitute.dll  and it have more priority than user library NSubstitute.dll

This class _NSubstitute.Core.ConfigureCall_ dont exists in NUnit build

**Comment by ghost** [comment]
Nice. So what can we do with it?

btw. I already made makefile x)

**Comment by VISTALL** [comment]
For now - remove library from NUnit/bin/lib/

Already considering logic of .NET loader for fix this issue
