### ISSUE TITLE
Previously written tests now showing NUnit.Framework.SyntaxHelpers warning.

### ISSUE THREAD

**Issue by MarcAtPlumbee** [consulo/consulo-nunit#6]
I am currently working in a CSharp-Unity project working with Consulo and have started getting an IDE warning in my unit tests with the following: Use 'NUnit.Framework.SyntaxHelpers'? since updating my plugins.   If I use the SyntaxHelpers import, then the build fails in the Unity Editor.  

Cheers,
Marc Trepanier

**Comment by VISTALL** [comment]
Can you show this warning ?

**Comment by MarcAtPlumbee** [comment]
![errorscreen](https://cloud.githubusercontent.com/assets/1300813/14986401/a9bb9154-1143-11e6-9037-7b640d660367.png)

This is new since updating to the current consulo and matching plugins.   Previously there was not a warning about needing to use SyntaxHelpers.  I suspect it is an issue with an old version of NUnit being used in Consulo, but I've not been able to find where to set this to a different version.

**Comment by VISTALL** [comment]
Looks like resolving bug in C#. I will check, maybe today

**Comment by MarcAtPlumbee** [comment]
Awesome!   Thanks for that.

**Comment by VISTALL** [comment]
Can you show error - when you add using 'SyntaxHelpers' ?

**Comment by VISTALL** [comment]
Not needed - i repeated

**Comment by VISTALL** [comment]
Fixed. Please update plugin after one hour

**Comment by MarcAtPlumbee** [comment]
Excellent!!  That is brilliant work in a very short time.  Thank you very much.
